### ISSUE TITLE
Python3 modules icalendar and recurring_ical_events are missing in hass.io run in docker

### ISSUE THREAD

**Issue by uherting** [KoljaWindeler/ics#4]
Thanks a lot for your work!

I installed the repository version 6e7ba7b via HACS without a problem.

On checking the configuration within hass.io (v0.107.5) though errors regarding a missing module were issued.

I started the shell in the homeassistent container and issued subseqently

- pip3 install icalendar
- pip3 install recurring_ical_events

The errors in the config were gone then.

Maybe you want to add a remark to the README.md file for the people who run hass.io in docker?

**Comment by KoljaWindeler** [comment]
Hi, thanks for your message. The dependencies are listed in the manifest and will be automatically installed once homeassistent restarts. 

So basically one has to reboot homeassistent twice:
1. Install the addon
2. Reboot so homeassistent will load the components and install the dependencies
3. Add the config 
4. Restart homeassistent 

Otherwise one will get errors during the config check. But that's the same for all custom components. 

I'll add something in the readme.
Kolja
